---
title: "miRNA_Target_Finder"
author: "Nick Werry"
date: "11/12/2020"
output: html_document
params:
  miRNA_A:
    label: "first miRNA of interest (hsa-miR-##-#p)"
    input: text
    value: ""
  miRNA_B:
    label: "second miRNA of interest (hsa-miR-##-#p)"
    input: text
    value: ""
  valResults: 
    label: "Validated interactions"
    value: TRUE
  preResults:
    label: "Predicted interactions" 
    value: TRUE
  numResults:
    label: "How many targets to return?"
    input: text
    value: 10
  saveFile:
    label: "Save output file of all data?"
    value: TRUE
  numDatabases:
    label: "ADVANCED: How many databases must predict?"
    input: slider
    min: 1
    max: 8
    step: 1
    value: 4

---

<!-- USE this line in the console to knit with custom parameters -->
<!-- rmarkdown::render("miRNA_Target_Finder", params = "ask") -->

```{r Setup, echo = FALSE}
library(knitr)

#Tidy output
opts_chunk$set(tidy = TRUE, cache=FALSE)

#Limit decimals
options(digits = 3) 
```

```{r Libraries, echo = FALSE, message = FALSE, warning = FALSE}
if ("tidyverse" %in% rownames(installed.packages()) == FALSE) {install.packages("tidyverse")}
library(tidyverse)
if ("BiocManager" %in% rownames(installed.packages()) == FALSE) {install.packages("BiocManager")}
library(BiocManager)
if ("multiMiR" %in% rownames(installed.packages()) == FALSE) {BiocManager::install("multiMiR")}
library(multiMiR)
if ("ggplot2" %in% rownames(installed.packages()) == FALSE) {install.packages("ggplot2")}
library(ggplot2)
if ("writexl" %in% rownames(installed.packages()) == FALSE) {install.packages("writexl")}
library(writexl)
```

```{r Parameters, echo = FALSE}
#Add miRNA parameters to properly formatted miRNA list
mirList <- vector(mode = "list")
for (miR in params){
  if (str_detect(miR, "miR")){
    mirList[miR] <- (ifelse(startsWith(miR, "hsa-"), miR, sprintf("hsa-%s", miR)))
  }
}

#Create string of abbreviated miRNA pairs as filename
mirListShort <- vector(mode = "character")
for (miR in params){
  if (str_detect(miR, "miR")){
    mirListShort[miR] <-  str_extract(miR, "(miR\\-)\\w+")
  }
}

#Visually appealing string of mirListShort
mirAmp <- paste(mirListShort, collapse = " & ")

#Variables for filenames
fileName <- sprintf("%s_Targets.xlsx", mirAmp)
```

### miRNA Targets\
#### `r if(params$valResult){sprintf("Top %s Validated Results", params$numResults)}`
```{r Validated, echo = F, eval = params$valResults}
#Get miRNA target data from validated databases
valid_data <- multiMiR::get_multimir(org = "hsa", mirna = mirList, table = "validated")

#Filter to ensure validated results and named genes
valid_df <- data.frame(valid_data@data[c(3,4,9,10)]) %>%
  filter(!(target_symbol == "")) %>%
  filter(type == "validated")

#Filter for unique entries, targeting by all input miRNAs
valid_cotarget <- mutate(valid_df[c(1:3)]) %>%
  distinct() %>%
  group_by(target_symbol) %>%
  mutate(miRNA_count = length(unique(mature_mirna_id))) %>%
  filter(miRNA_count == length(mirList))

#Rank results according to non-redundant records
valid_cotarget_ranked <- as.data.frame(table(valid_cotarget$target_symbol)) %>%
  arrange(desc(Freq)) %>%
  rename("gene"="Var1","reports"="Freq")

#Output top result
head(valid_cotarget_ranked, params$numResults)
```

#### `r if(params$preResult){sprintf("Top %s Predicted Results", params$numResults)}`
```{r Predicted, echo = FALSE, eval = params$preResults}
#Get miRNA target data from predicted databases
predict_data <- multiMiR::get_multimir(org = "hsa", mirna = mirList, table = "predicted")

#Filter to ensure predicted results and named genes
predict_df <- data.frame(predict_data@data[c(1,3,4,7,8)]) %>%
  filter(!(target_symbol == "")) %>%
  filter(type == "predicted")

#Filter for number of databases predicting targeting
predict_databases <- mutate(predict_df[c(1:4)]) %>%
  group_by(mature_mirna_id, target_symbol) %>%
  mutate(indv_database_count = length(unique(database))) %>%
  group_by(target_symbol) %>%
  mutate(total_database_count = length(unique(database))) %>%
  distinct()

#Filter for targeting by all input miRNAs
predict_databases_cotargets <- predict_databases %>%
  filter(indv_database_count >= params$numDatabases) %>%
  group_by(target_symbol) %>%
  mutate(miRNA_count = length(unique(mature_mirna_id))) %>%
  filter(miRNA_count == length(mirList))

#Filter based on input number of databases, calculate mean rank across databases
predict_rank <- predict_databases_cotargets %>%
  group_by(mature_mirna_id) %>%
  group_by(database) %>%
  mutate(rank = order(order(database))) %>% #Follow default score ranking
  group_by(target_symbol) %>%
  mutate(mean_rank = mean(rank)) %>%
  arrange(mean_rank) %>%
  arrange(desc(total_database_count))

#Clean results to show top interactions based on mean ranking
predict_rank_genes <- predict_rank %>%
  dplyr::select(target_symbol, total_database_count, mean_rank) %>%
  distinct()

#Plot database restriction to see how many interactions are being ignored
ggplot(predict_databases, mapping = aes(indv_database_count)) +
  geom_histogram(binwidth = 1) +
  scale_x_continuous(breaks = (1:8)) +
  geom_vline(xintercept = (params$numDatabases - 0.5), colour = "red") +
  ggtitle(sprintf("Predicted results filtered for presence in %s or more databases", params$numDatabases))

#Output result
head(predict_rank_genes, params$numResults)
```

```{r Save Results, echo = F, eval = params$saveFile}
#Run analyses if not performed above
if (params$valResults == FALSE){
valid_data <- multiMiR::get_multimir(org = "hsa", mirna = mirList, table = "validated")
valid_df <- data.frame(valid_data@data[c(3,4,9,10)]) %>%
  filter(!(target_symbol == "")) %>%
  filter(type == "validated")
valid_cotarget <- mutate(valid_df[c(1:3)]) %>%
  distinct() %>%
  group_by(target_symbol) %>%
  mutate(miRNA_count = length(unique(mature_mirna_id))) %>%
  filter(miRNA_count == length(mirList))
valid_cotarget_ranked <- as.data.frame(table(valid_cotarget$target_symbol)) %>%
  arrange(desc(Freq)) %>%
  rename("gene"="Var1","reports"="Freq")
}
if (params$preResults == FALSE){
predict_data <- multiMiR::get_multimir(org = "hsa", mirna = mirList, table = "predicted")
predict_df <- data.frame(predict_data@data[c(1,3,4,7,8)]) %>%
  filter(!(target_symbol == "")) %>%
  filter(type == "predicted")
predict_databases <- mutate(predict_df[c(1:4)]) %>%
  group_by(mature_mirna_id, target_symbol) %>%
  mutate(indv_database_count = length(unique(database))) %>%
  group_by(target_symbol) %>%
  mutate(total_database_count = length(unique(database))) %>%
  distinct()
predict_databases_cotargets <- predict_databases %>%
  filter(indv_database_count >= params$numDatabases) %>%
  group_by(target_symbol) %>%
  mutate(miRNA_count = length(unique(mature_mirna_id))) %>%
  filter(miRNA_count == length(mirList))
predict_rank <- predict_databases_cotargets %>%
  group_by(mature_mirna_id) %>%
  group_by(database) %>%
  mutate(rank = order(order(database))) %>% #Follow default score ranking
  group_by(target_symbol) %>%
  mutate(mean_rank = mean(rank)) %>%
  arrange(mean_rank) %>%
  arrange(desc(total_database_count))
predict_rank_genes <- predict_rank %>%
  dplyr::select(target_symbol, total_database_count, mean_rank) %>%
  distinct()
}

writexl::write_xlsx(x = list(Predicted = predict_rank_genes, Validated = valid_cotarget_ranked), path = fileName)
```